languaje: node_js

cache: 
  direcctories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git: 
  depth: 3

script: 
  - yarn build

notifications:
  email:
    recipients:
      - juandnb@outlook.es
      - juanmothy182@gmail.com
    on_success: always
    on_failure: always


deploy: 
  provider: pages
  skip-cleanup: true
  kepp-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del Proyecto"
  on:
     branch: master